name: onyx_plugin
description: This plugin integrates the onyx fingerprint camera api with flutter.
version: 7.1.1
homepage: https://diamondfortress.com/
repository: https://github.com/DFTinc/onyx-flutter-package/ 
issue_tracker: https://github.com/DFTinc/onyx-flutter-package/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.dft.onyx.plugin
        pluginClass: OnyxPlugin
      ios :
        package: com.dft.onyx.plugin
        pluginClass: OnyxPlugin
